version: '2'

services:
  app:
    image: work-framework
    build:
      context: .

  provisioner:
    image: akino1976/aws-local-provisioner
    environment:
      S3_HOST: http://aws-mock:3000
      SQS_HOST: http://aws-mock:3001
      SNS_HOST: http://aws-mock:3003
      AWS_LOCAL_TEMPLATE_PATH: /templates/aws-mock-resources.yaml
    volumes:
      - ./aws-mock-resources.yaml:/templates/aws-mock-resources.yaml
    depends_on:
      - aws-mock

  aws-mock:
    image: localstack/localstack:0.8.6
    environment:
      DEFAULT_REGION: eu-west-1
      SERVICES: s3:3000,sqs:3001,ssm:3002,sns:3003,kinesis:3004,dynamodb:3005
      FORCE_NONINTERACTIVE: 'true'
      HOSTNAME: aws-mock
      HOSTNAME_EXTERNAL: aws-mock
      DEBUG: 0

  storage:
    image: microsoft/mssql-server-linux:2017-CU13
    ports:
      - 1433:1433
    environment:
      MSSQL_SA_PASSWORD: Test-password
      ACCEPT_EULA: Y
      PATH: /opt/mssql-tools/bin:/opt/mssql/bin:$PATH
      TZ: Europe/Stockholm

  db-migrator:
    image: database-migrator:${VERSION}
    build:
      dockerfile: ./migrator/Dockerfile
      context: .
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      DB_USERNAME: ${DB_USERNAME}
      DB_ENDPOINT: ${DB_ENDPOINT}
      DB_PASSWORD_KEY: ${DB_PASSWORD_KEY}
    depends_on:
      - storage

